name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    # Add permissions required for release management
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build and package
        run: |
          make
        env:
          VERSION: ${{ github.event.release.tag_name }}

      - name: Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          files: |
            ec2-to-ova.tar.gz.sha256sum
            ec2-to-ova.tar.gz